### ISSUE TITLE
dns within chroot not working when using 20.04 live server iso

### ISSUE THREAD

**Issue by jserviceorg** [64kramsystem/zfs-installer#228] opened 2021-07-08 14:00 UTC
i am trying to install a 20.04 server, booted from a 20.04 live server iso image. when the installer created the jail, it suddenly broke because dns is not working within the chroot.

a

**Comment by saveriomiroddi** [comment] 2021-07-08 15:12
Hello! I need the logs in order to investigate.

**Comment by saveriomiroddi** [comment] 2021-07-08 15:13
This may be a duplicate of #166, but I don't have enough information to be certain.

**Comment by jserviceorg** [comment] 2021-07-13 10:53
i finally debugged everything, will get back to this ticket later with explanation & patch

**Comment by saveriomiroddi** [comment] 2021-07-13 11:07
> i finally debugged everything, will get back to this ticket later with explanation & patch

Thanks! :+1: :star_struck:

**Comment by jserviceorg** [comment] 2021-07-23 09:45
see my forked repo https://github.com/jserviceorg/zfs-installer

**Comment by saveriomiroddi** [comment] 2021-07-26 21:12
> see my forked repo https://github.com/jserviceorg/zfs-installer

Hello! Can you give me some context? Since this is a significant change, I'd like to understand it fully.

The mechanic is evident - bind the the jail `/run` to the hosts `/run`. However, how does it interact with the existing context of `run`? I know it's transient, since it's a live CD, but I wonder if some existing content may confuse programs running inside the jail.

**Comment by 64kramsystem** [comment] 2021-08-30 08:48
Closing for inactivity.

**Closed by 64kramsystem** 2021-08-30 08:48 UTC
Labels: requires feedback
